### ISSUE TITLE
反馈一下，z9s，2.1.30正式版，刷好后smb共享文件打开里面是空白的。看挂载点应该是对的，官方op正常

### ISSUE THREAD

**Issue by sw19999** [jjm2473/rtd1295-openwrt18-porting#1]

**Comment by sw19999** [comment]
顺便问一下，nfs连接提示用户名密码，输入root密码是错误的。苹果macOS连接afp共享也是提示需要用户名密，用不了

**Comment by jjm2473** [comment]
transmission和samba是我最常用的功能, 肯定都是重点测试的功能, 一般都不会有问题.
可以重置下openwrt再测试, 或者先看看下面的提示.

首先, 看一下我的[笔记](https://github.com/jjm2473/rtd1295-openwrt18-porting/blob/z9s_luci/docs/porting.md)的最后几行, 是不是属于这里的情况, samba导出的文件夹需要是挂载点, 而且挂载点的所有者需要是nobody, 因为客户端连接以后samba服务端会切换到nobody用户, 如果nobody用户没有权限访问你提供的挂载点, 那就变成空的了. 另外, 如果导出/mnt, 那么客户端挂载/mnt以后只能看到挂载点文件夹(例如/mnt/sda1)而看不到里面的文件.

NFSD的权限校验更是严格, 连/mnt都不能导出, 只能导出其中的挂载点, 例如/mnt/sda1, 同样挂载点需要nobody用户能访问. 因为/mnt肯定不能导出, 所以连接/mnt会提示错误或没权限.

afp(timemachine)的话, 没怎么测试, 貌似samba4本身已经支持了timemachine(去samba的配置页面看看), 所以afp已经没什么用了.

最后, 如果会用ssh的话, 可以提供这些命令的输出给我排查.
`mount`
`cat /etc/config/samba4`
`cat /etc/config/nfsd`

**Comment by jjm2473** [comment]
afp不知道怎么使用, 有什么测试方法也请提供下.

**Comment by sw19999** [comment]
挂载当时有留意过，一开始我就是怀疑挂载点错误，就是：/mnt/sata1 这样的。当时还去挂载那里复制路径过来smb共享这边测试无效。权限没注意看都是使用默认设置。

重置过设置再刷你的op的。会用ssh，机器在家，晚上可以测试。

**Comment by jjm2473** [comment]
刷完后再重置一次试试，因为刷机前还是进了一次系统，可能留下错误的配置

**Comment by sw19999** [comment]
测试结果正常了，应该就是你上面说的必须刷好op之后，重置一下op设置才会正常，我直接刷完op重启进入系统，再次刷入op重置包后重启正常了。但是nfs共享设置连接不上，提示：您没有访问此服务器的权限。共享目录：/mnt/sataa1 ，监听IP：* ，共享选项：ro,insecure,sync,anonuid=1023,all_squash

**Comment by sw19999** [comment]
root@OpenWrt:~# mount
/dev/root on /rom type squashfs (ro,relatime)
devtmpfs on /rom/dev type devtmpfs (rw,seclabel,relatime,size=812372k,nr_inodes=203093,mode=755)
tmpfs on /rom/android type tmpfs (ro,seclabel,noatime,size=10240k)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
sysfs on /sys type sysfs (rw,seclabel,nosuid,nodev,noexec,noatime)
cgroup on /sys/fs/cgroup type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,net_prio,pids)
tmpfs on /tmp type tmpfs (rw,seclabel,nosuid,nodev,noatime)
/dev/mmcblk0p10 on /overlay type ext4 (rw,seclabel,relatime,data=ordered)
overlayfs:/overlay on / type overlay (rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,size=512k,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,nosuid,noexec,relatime,mode=600,ptmxmode=000)
debugfs on /sys/kernel/debug type debugfs (rw,seclabel,noatime)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)

**Comment by sw19999** [comment]
root@OpenWrt:~# cat /etc/config/samba4

config samba 'config'
        option enabled '1'
        option workgroup 'WORKGROUP'
        option description 'Samba on OpenWrt'
        option charset 'UTF-8'
        option homes '0'
        option interface 'lan wlan p2p'
        option name 'openwrt'
        option macos '0'

config sambashare '58CC2492CC246C86'
        option name 'Disk_sataa1'
        option path '/mnt/sataa1'
        option state 'a'
        option read_only 'no'
        option guest_ok 'yes'
        option guest_only 'yes'

**Comment by sw19999** [comment]
root@OpenWrt:/mnt# cat /etc/config/nfsd

config nfsd_mount
        option share_ip '*'
        option share_options 'ro,insecure,sync,anonuid=1023,all_squash'
        option share_dir '/mnt/sataa1'

**Comment by sw19999** [comment]
重启一下共享里面又没有文件了。才开心了不到几分钟。ssh代码贴在上面了。没有挂载SATAA1。

**Comment by sw19999** [comment]
系统自带的重置op选择是无效的。点了根本不会重置。smb共享速度也不快，千兆局域网复制文件只有50m之内。官方的版本80m-110m左右。期待兄弟继续优化改善。

**Comment by jjm2473** [comment]
系统自带的重置op一开始没支持, 现在1.3版已经支持了. smb的速度的话, 我没修改smb服务, 用的是op官方的samba4 (Z9S原版的smb是samba3), 1.3禁用了防火墙, 也许会好些, 不过我家只有无线网络, 无法测试高速率传输.

前面贴的mount没有sataa1, 所以也不能帮你判断是不是权限问题, 建议挂载好sataa1再测试各种功能, 测试有问题就把前面说的环境信息发给我. 我日常就是使用这个系统, 至少有一周了, smb一直都是正常的.

**Comment by jjm2473** [comment]
要排查NFS的问题的话, 还需要提供 ```exportfs``` 命令的输出.

**Comment by sw19999** [comment]
nfs暂时不解决也行。我这边测试是smb刷完重置后正常使用。盒子选择重启一下，硬盘就挂载不上了。

**Comment by jjm2473** [comment]
刷完是需要重置的, 因为刷机前还是运行原版的OpenWrt, 可能会生成不兼容的配置. 

综合判断, smb文件夹打开以后是空白的根本原因不在smb服务, 而是硬盘挂载的问题(估计NFS也是一样).

至于硬盘挂载不上, 一个可能的原因是你的硬件变动(例如插拔过U盘)导致设备路径变了(例如sataa1变成satab1), 启动时就找不到设备了, 在“挂载点”页面点击“生成配置”可以重新识别设备, 或者手动指定UUID作为设备, 手动指定挂载点, 这样就算设备变化也还能正常挂载. 
之所以使用设备路径而不是UUID作为自动挂载的依据, 主要还是为了兼容Zidoo官方的挂载方式, 如果我改成了UUID挂载, 可能transmission就找不到文件了.

**Comment by sw19999** [comment]
刷完后重置，自动重启了。进入op可以看到挂载sata硬盘好了，smb映射正常，局域网也能看到硬盘文件。

现在马上重启，只有sata硬盘1个wd 8t，刷op前后，或者重启前后都没有接入过任何其它设备。
重启后挂载没有了，也许是兼容问题。

**Comment by jjm2473** [comment]
我家只有一个1T的硬盘, 没出什么问题. 也许8T的确实太大, 开机过程中没那么快就识别到, 挂载流程却已经过了. 重置后第一次启动之所以能挂载成功, 应该是第一次启动花的时间比较长, 有足够的时间识别硬盘.

执行这几条命令看看:
```
ls /dev/ | grep sata
cat /etc/config/fstab
/etc/init.d/fstab start
```

**Comment by jjm2473** [comment]
如果上面的命令挂载成功了, 那么可以在“启动项”的“本地启动脚本”添加以下命令
```
sleep 5

/etc/init.d/fstab start

exit 0
```
这样的话, 会在启动后等待5秒再尝试挂载一次.

**Comment by sw19999** [comment]
发馈一下：挂载成功了。就是在 启动项”的“本地启动脚本，加入延迟这些命令有效。估计就是硬盘容量太大，挂载速度问题。

今天测试500g笔记本硬盘重启几次都可以正常挂载。我的wd 8t硬盘重启第二次就挂载失败。又去公司借了一个4t的监控硬盘测试。跟8t的现象一样。现在加了脚本后重启几次都正常了。

另外smb的速度正常了。80m-110m跳动

**Comment by jjm2473** [comment]
好的, 谢谢反馈! 我关闭这个issue了.
