### ISSUE TITLE
小睿私人云刷入后无法启动android

### ISSUE THREAD

**Issue by hadeskaiser** [jjm2473/rtd1295-openwrt18-porting#10]
私人云刷如bpi-w2后，ssh到openwrt后，直接dd刷入对应分区后，openwrt可以正常使用。但是android启动不了，插上hdmi无显示，接ttl查看启动信息发现卡住了无法进去到kylin32控制台。

**Comment by jjm2473** [comment]
没研究过香蕉派的系统，也没有小睿云，看有没有人回答下

**Comment by cooljc123** [comment]
有需要私人雲的squashfs1.img或者分區的DUMP嗎?

**Comment by jjm2473** [comment]
私人云原版系统的squashfs1.img之前在另一个issue提供了，也做了一个对应的镜像。但是基于bpi-w2的可能不一样，而且bpi-w2还有Android 6.0和7.0两个版本。如果bpi-w2的镜像都能刷，估计Z9S的也能刷。

**Comment by szq0076** [comment]
> 
> 
> 有需要私人雲的squashfs1.img或者分區的DUMP嗎?

我刷了bpi-w2正想找私人云的原版备份刷回去那,可以的话发给我 13428400771@139.com,qq29679228

**Comment by jjm2473** [comment]
联系下这个issue的作者  https://github.com/jjm2473/rtd1295-openwrt18-porting/issues/8

**Comment by szq0076** [comment]
谢谢! 开始继续折腾!



13428400771@139.com
 
发件人： 练亮斌
发送时间： 2019-09-03 09:28
收件人： jjm2473/rtd1295-openwrt18-porting
抄送： szq0076; Comment
主题： Re: [jjm2473/rtd1295-openwrt18-porting] 小睿私人云刷入后无法启动android (#10)
联系下这个issue的作者 #8
