### ISSUE TITLE
签名

### ISSUE THREAD

**Issue by Alexey71** [jjm2473/rtd1295-openwrt18-porting#11]
您好，请告诉我在哪里获取updater.zip签名，以便在安装过程中没有错误？

**Comment by jjm2473** [comment]
使用signapk进行签名：`java -jar signapk.jar -w --disable-v2  testkey.x509.pem testkey.pk8 ota.zip ota.signed.zip`，
testkey可以从这里下载：
https://android.googlesource.com/platform/build/+/refs/heads/master/target/product/security/
