### ISSUE TITLE
 我是开博尔的Q30Plus 是刷RTD1296的包吗？

### ISSUE THREAD

**Issue by yuikzne** [jjm2473/rtd1295-openwrt18-porting#13]

**Comment by jjm2473** [comment]
看看安卓系统的版本

**Comment by yuikzne** [comment]
安卓7.1的

**Comment by jjm2473** [comment]
那就是刷rtd1296的，也就是z9s那个版本

**Comment by yuikzne** [comment]
您好楼主，有个问题想请教一下，Z9s通过另一台Q30访问，没有写入权限，但通过电脑可以完全读取和写入，是Z9s上哪个权限没有打开吗？应该怎么设置，谢谢了！

**Comment by yuikzne** [comment]
补充一下现在两台机器都是刷的RTD1296 1.51版

**Comment by jjm2473** [comment]
你是说samba服务不能写入吗?是不是用特定用户登录了

**Comment by yuikzne** [comment]
SAMBA和NFS都不能写入，没有用特定的帐户，就默认

**Comment by jjm2473** [comment]
电脑上却能写入吗, 奇怪

**Comment by yuikzne** [comment]
电脑上能写入，我电脑下载的电影能直接存在Z9S的硬盘上，用Q30 拷贝文件到Z9S就不行，说是写入权限没有打开

**Comment by yuikzne** [comment]
说明Z9s的部分帐户写入权限没有打开，这个应该怎么设置呢？谢谢！

**Comment by jjm2473** [comment]
你是拷到Z9S的同一个文件夹吗

**Comment by yuikzne** [comment]
不是同个文件夹，现我把Z9S 的SAMAB的强制ROOT勾上，通过SAMAB方式已经可以写入，但NFS传输还是不能写入

**Comment by yuikzne** [comment]
现在问题应该是NFS服务器没有写入权限

**Comment by jjm2473** [comment]
看下是不是属于这里的情况 https://github.com/jjm2473/rtd1295-openwrt18-porting/blob/z9s_luci/docs/porting.md#%E7%BD%91%E7%BB%9C%E5%85%B1%E4%BA%AB%E7%9A%84%E9%99%90%E5%88%B6

**Comment by jjm2473** [comment]
如果不清楚的话, 把挂载表和NFS的配置发出来看看

**Comment by yuikzne** [comment]
共享的目录 /mnt/sataa1
 
 
监听IP *
 
 
共享选项 
 ro,insecure,sync,anonuid=1023,all_squash

**Comment by yuikzne** [comment]
共享的目录 /mnt/sataa1

监听IP *

共享选项
ro,insecure,sync,anonuid=1023,all_squash

**Comment by jjm2473** [comment]
/mnt/sataa1的挂载配置是怎样的, 如果挂载的权限不对也没法用NFS的

**Comment by yuikzne** [comment]
文件系统 ：ufsd
 挂载选项：force,nls=utf8,uid=1023,gid=1023,umask=0007,noatime,user_xattr=1

**Comment by jjm2473** [comment]
注意到你的NFS选项中有“ro”, 改成“rw”试试
