### ISSUE TITLE
如何给x9s强制刷机，官方教程说不支持强制刷机了

### ISSUE THREAD

**Issue by ihipop** [jjm2473/rtd1295-openwrt18-porting#2]
![image](https://user-images.githubusercontent.com/423077/56092024-5fd9a200-5ee9-11e9-88f9-39aa21f5c33f.png)

**Comment by jjm2473** [comment]
上次看到论坛有人讨论强刷包下不了，我测试了一下是百度云的问题，不是zidoo官方失效了下载链接。
当时论坛楼主还提到可以从英文的教程那里找到另一个非百度云的链接，从那里可以下载。
另一个方法就是在论坛或者群里发帖寻找强刷包。

**Comment by ihipop** [comment]
@jjm2473 给官方去了邮件，说不支持强刷，让我返厂。

**Comment by jjm2473** [comment]
官方不是什么都了解的，别迷信官方权威，x9s使用的是realtek的方案，要问官方的话，realtek也要包括进去。而且回复你的可能是不了解情况的客服，还是要自己去探索下。

**Comment by ihipop** [comment]
链接: https://pan.baidu.com/s/1WJIQHw-ULw_--bb2dc9SSA 提取码: w4r2

从国外论坛拿到了两个文件 
```
0a906b46340a1bf8fa6a79c3da199491  install-ZIDOO_X9S-v1.4.12-201708181828-USB.img
f95939fa8e16c374bd15a8c4657fa669  ZIDOO_X9S-v2.1.1-201808020940-usb.img
```
分享出来吧。
