### ISSUE TITLE
Z9S的openwrt18版本

### ISSUE THREAD

**Issue by szbiding** [jjm2473/rtd1295-openwrt18-porting#3]
有几个问题：
1、smb共享功能不能用，挂载点和SMB列表都是正常的，就是共享不行,打开SMB后里面一片空白(已解决必须再重置一下)
2、开启FTP后，ftp功能还是不能用(已解决必须再重置一下)
3、挂载点显示在挂载列表，但是必须要进挂载点编辑一下，才会显示到已挂载列表
4、aria2不管怎么勾选，一直是显示aria2未运行，但是启动项是开启的，也打不开客户端页面

我用的是1.4版的那个不带flexget的那个版本

建议：
1、是否可以新增一个磁盘管理，这个如果遇到全新的SATA硬盘，这个时候要格式化EXT4就有点难度了

**Comment by jjm2473** [comment]
3.可能是因为重置以后第一次开机就插入了硬盘, 这个是不会自动挂载的(因为有可能是系统分区), 不需要编辑, 在前面打勾保存就可以了.

4.启用以后, 先在启动项那边手动启动吧, 之后重启应该会自动启动了, 如果重启没生效再排查吧.

1和2, 可能是挂载的问题导致的, 如果挂载好了以后还是空白, 那执行`mount`和`ls -l /mnt/`, 并把执行结果贴出来.

建议1的话, 因为Openwrt官方软件库里没有磁盘管理, 可能之后我会从Zidoo的固件移植过来.

**Comment by szbiding** [comment]
1,2已经解决   必须要要重置一下openwrt才正常

**Comment by jjm2473** [comment]
哦, 第一次刷我的这个包是需要重置的, 因为之前的系统配置可能不兼容, 建议到项目首页仔细看看[安装方法](https://github.com/jjm2473/rtd1295-openwrt18-porting#%E4%BA%8C%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95)

**Comment by szbiding** [comment]
非常感谢，就是那个aria2的还是没有启动起来

**Comment by jjm2473** [comment]
刚刚检查了一下, 的确少了几行代码, 导致修改aria2的配置不能自动生效. 
临时方案还是先改好aria2的配置, 然后在“启动项”找到aria2, 点一下启动, 这样就手动启动了, 以后重启盒子应该会自动启动aria2的. 
还有一个方案是在软件包那里重新安装"luci-app-aria2"(卸载, 然后更新软件列表, 然后安装).

**Comment by szbiding** [comment]
现在有一个问题，挂两个硬盘的时候，每次重启，经常会有盘符挂载不上，要手动去编辑他的挂载点，不知道这个是什么问题，另外transmission文档  是否还需要添加sleep

**Comment by jjm2473** [comment]
先升级到1.5版吧, 启动加了几秒延时 https://github.com/jjm2473/rtd1295-openwrt18-porting#15-2019-05-11

我只有一块1T的硬盘, 有些问题实在测不出来, 我觉得可能你的硬盘多, 重启之后设备路径变了, 挂载就乱了, 你可以指定按UUID挂载, 挂载点也指定特殊的, 例如/mnt/download, 这样就可以避免自动判断挂载点.

transmission有什么问题?

**Comment by szbiding** [comment]
升级包失败

**Comment by jjm2473** [comment]
你的官方底包是什么版本的

**Comment by jjm2473** [comment]
下载到的文件md5是34de16a03115101573384494cc9a88d4吗?

**Comment by szbiding** [comment]
那个transmission 你这个版本是否还需要添加sleep 60，要不然好像重启后不能保存任务，添加了sleep 60之后  那个启动项就打不开了，X20PRO的2.2.61，

**Comment by szbiding** [comment]
82c16a4b0c4eefd6305bdc66e80447f10b370ce0

**Comment by jjm2473** [comment]
transmission一直都不用sleep啊

**Comment by jjm2473** [comment]
哪个文档说要sleep的

**Comment by szbiding** [comment]
原来官方版本就要加  不加重启任务就不见了  必须要添加sleep后 才行   要不然就要进启动项重启transmission

**Comment by jjm2473** [comment]
哦, 可能是硬盘挂载太慢, 想等待硬盘. 你的硬盘是有多大啊.

**Comment by jjm2473** [comment]
升级包失败的问题解决了吗

**Comment by szbiding** [comment]
挂了4个硬盘
基本都是2T以上

**Comment by szbiding** [comment]
没有解决升级包问题

**Comment by jjm2473** [comment]
那还真是挺大的. 

在“启动项”的“本地启动脚本”添加以下命令
```
sleep 20

/etc/init.d/transmission stop
sleep 2
/etc/init.d/transmission start

exit 0
```
这样的话, 会在启动后等待20秒重启transmission.

不过还是要看挂载是不是最后成功了, 如果挂载有问题, sleep多久都没用.

**Comment by jjm2473** [comment]
你下载的是哪个包啊, 校验md5了没, 或者包里面有哪些文件.

**Comment by jjm2473** [comment]
Z9S的包我在自己机器上刷过的(我的底包是2.1.40), 一般没什么问题, 除非Zidoo改了OTA的签名.

**Comment by szbiding** [comment]
估计是    刷不成功  你原来1.4的可以    1.5的不行  提示失败

**Comment by jjm2473** [comment]
是不是下错包了, 有两个是源码包.

**Comment by jjm2473** [comment]
刷1.4之后有更新官方OTA吗

**Comment by szbiding** [comment]
我看看

**Comment by jjm2473** [comment]
直链 https://github.com/jjm2473/rtd1295-openwrt18-porting/releases/download/1.5_full/update.op18_1.5.signed.zip

**Comment by szbiding** [comment]
X20PRO是1296的   用这个1295的可以吗

**Comment by jjm2473** [comment]
反正校验一下md5就知道了, 不管是下错包还是包损坏, 一眼就能看出来.

**Comment by jjm2473** [comment]
Android 7.1.1 不能用 1295

**Comment by jjm2473** [comment]
注意看说明 https://github.com/jjm2473/rtd1295-openwrt18-porting#%E5%8F%91%E5%B8%83

**Comment by szbiding** [comment]
好的  谢谢  我试试

**Comment by jjm2473** [comment]
不是按CPU, 两个CPU都是a53, 而是按Android版本和Linux内核版本区分的

**Comment by jjm2473** [comment]
可能对其他用户有帮助, 归档并Close了
