### ISSUE TITLE
X9S最新的1.5版里的Aria是否可以编译加入支持磁力链？

### ISSUE THREAD

**Issue by mayaxcn** [jjm2473/rtd1295-openwrt18-porting#5]
另外可否像transmission那样加入自定义的UI目录可自行填写？谢谢。

**Comment by jjm2473** [comment]
加磁力链我可以试试，不过加自定义UI路径的功能其实可以提到openwrt官方issue，这是一个通用的功能。

**Comment by jjm2473** [comment]
我看默认有支持metalink，也许你可以试试支不支持磁力链接

**Comment by jjm2473** [comment]
我测试过了, 支持磁力链, 不过DHT初始化都比较慢, 如果之前没下过BT会很久都不能初始化, 要先下几个BT种子, 才能比较快找到DHT的其他用户, 之后aria2会保存这些用户, 下次下载磁力链就能比较快找到对应的用户了.

**Comment by jjm2473** [comment]
UI目录自定义应该是不行的, 因为是共用luci后台的web服务, 实际上你把UI文件放在/www/ui/下就可以了, 不需要指定. transmission是自己提供了一个web服务, 所以根目录是它自己决定的.

**Comment by mayaxcn** [comment]
一开始没有找到aria的Web界面在哪个文件夹，后来找到了已经替换为自己的Web UI

**Comment by jjm2473** [comment]
aria2的webui其实跟aria2本身没多大关系，就算盒子里没装aria2，也可以单独装webui，放在/www目录下就行了（luci本身就提供一个简单的web服务器）

**Comment by mayaxcn** [comment]
另外想知道transmission的WEBUI具体位置是在目录的哪？

**Comment by jjm2473** [comment]
默认在 /usr/share/transmission/web

**Comment by mayaxcn** [comment]
Got it. thanks
