### ISSUE TITLE
在安卓机器上恢复出厂设置后系统无法启动

### ISSUE THREAD

**Issue by scxhwhb** [jjm2473/rtd1295-openwrt18-porting#8]
机器是小睿私人云，一个矿难机器所以非常便宜，RTD1296+4G+16G的，因为系统自带的安卓是6.0.1，所以尝试刷了x9s的。开始op无法重置，因为刷之前可以通过adb reboot recovery的方式进到recovery刷OTA包，但是刷完过后就无效了，最后用op下的reset_system脚本重置成功了，而且机器各方面都正常。
在之后，在安卓系统里面运行了一次出厂设置，机器就卡在第一屏无法启动了。
目前能通过TTL进入到op的安全模式，也能进入到一个能看到init.rc的模式。
新机器刷机的风险我知晓，在这里也不是因为别的什么，只是想问下是否有解决方案，作为一个半吊子程序猿，目前的情况实在无能为力了。
[小睿TTL.txt](https://github.com/jjm2473/rtd1295-openwrt18-porting/files/3250129/TTL.txt)

**Comment by jjm2473** [comment]
有点神奇，重置以后反而启动不了。


我看日志好像是内核模块加载失败，你有原版的OTA包吗，提取里面的squashfs1.img给我，如果没有这个文件再尝试其他方法吧。


nasetc这个分区挂载是不是有点问题，也可以尝试格式化这个分区。

**Comment by jjm2473** [comment]
还有用`uname -a`命令看看内核版本

**Comment by scxhwhb** [comment]
> 还有用`uname -a`命令看看内核版本

内核版本是一致的，这个之前就核对过，这个机器没有原版系统，所以也没有OTA包，不过我还有个机器，需要哪些文件我可以提取出来。

**Comment by jjm2473** [comment]
OK，如果还有机器，那你看能不能提取squashfs格式的分区，或者你就对比下两台机器`/lib/modules/`目录里面有什么不一样。（也许我应该写个替换和打包教程）

**Comment by scxhwhb** [comment]
> OK，如果还有机器，那你看能不能提取squashfs格式的分区，或者你就对比下两台机器`/lib/modules/`目录里面有什么不一样。（也许我应该写个替换和打包教程）

方便说下怎么提取吗，我只会ssh到op里面去。

**Comment by scxhwhb** [comment]
> OK，如果还有机器，那你看能不能提取squashfs格式的分区，或者你就对比下两台机器`/lib/modules/`目录里面有什么不一样。（也许我应该写个替换和打包教程）

方便说下怎么提取吗，我只会ssh到op里面去。

**Comment by jjm2473** [comment]
先上班了，晚点聊，你可以把QQ号发我的邮箱先

**Comment by jjm2473** [comment]
### 这个设备的内核模块跟X9S不一样, 重新打包了一个, 之后有相同设备的可以用这个包.

https://github.com/jjm2473/rtd1295-openwrt18-porting/releases/tag/xiaoray_1.5_full
